### ISSUE TITLE
Tab context menu goes off-screen

### ISSUE THREAD

**Issue by repaxan** [Croydon/vertical-tabs-reloaded#147]
Add-on version: 0.9.1
Firefox version: 57
OS + OS-Version: Windows 10

The little right-click context menu isn't smart enough to flip in a different direction if opened too close to the edge.

![](https://i.imgur.com/q00LqK7.png)

**Comment by codecat** [comment]
I'm curious, I assume this is some kind of html context menu rather than a native OS context menu? Is it not possible to make a native-OS context menu in the new Firefox API?

**Comment by Croydon** [comment]
> I'm curious, I assume this is some kind of html context menu rather than a native OS context menu?

Yes, it's a custom HTML context menu.

> Is it not possible to make a native-OS context menu in the new Firefox API?

It is, but as a result you would get all website related context menu entries and at the very end a single VTR entry which has all options as a sub-menu. This would only confuse people and the VTR options wouldn't be nice to reach.

Related bugzilla bugs, which could change that: https://bugzilla.mozilla.org/show_bug.cgi?id=1397249 (which is already denied) & https://bugzilla.mozilla.org/show_bug.cgi?id=1280347 (which I'm still thinking will get a denied at some point as well).

This bug here is annoying as well of course, but it's solveable from our side in opposition to the bugs mentioned above.
