### ISSUE TITLE
Dark/Linux/Light Theme: Unwanted white horizontal bar at bottom

### ISSUE THREAD

**Issue by Croydon** [Croydon/vertical-tabs-reloaded#16]
There is a persistent white horizontal line at the bottom of the browser windows.
Found out why and remove it.

**Comment by Keith94** [comment]
Hi. So the issue seems to be caused by this CSS rule here:

https://github.com/Croydon/vertical-tabs-reloaded/blob/fixstuff/data/theme/base.css#L10

When commented, the white bar is no longer created when hovering over links.

Also the rest of the code related to the `statuspanel` may be obsolete as well, such as the ones found in `data/template/basic/index.css`

**Comment by Croydon** [comment]
@Keith94 You are right, just removing all styling rules related to the `statuspanel` seem to do the trick and it doesn't seem to break anything. If I should miss something then users will start complaining anyway I guess :laughing:.

It is funny how many bugs can be resolved in this add-on by removing code. Ancient code base... :flushed:
