### ISSUE TITLE
Please maintain a version for Waterfox

### ISSUE THREAD

**Issue by juanitogan** [Croydon/vertical-tabs-reloaded#166]
Add-on version: 0.8.5.2
Firefox version: Waterfox 56.0.1
OS + OS-Version: Win 10
Other tab + user interface related add-ons: 

Please add a link to your main page and other info pages for the latest version that works with Waterfox -- especially since switching from Firefox to Waterfox is the only way to hide the top tab bar now.  Currently, this version works well with Waterfox:

https://addons.mozilla.org/firefox/downloads/file/736688/vertical_tabs_reloaded-0.8.5.2-fx-windows.xpi?src=version-history

**Comment by grahamperrin** [comment]
> … this version works well with Waterfox: …

0.8.5.2 is critically bugged by #42, which is not always avoidable (and I don't expect a fix).

**Comment by grahamperrin** [comment]
> … critically bugged by #42, …

Strike that! 

As far as I can tell, recent versions of Waterfox are no longer prone to crashing when symptoms occur with legacy version 0.8.5.2 of Vertical Tabs Reloaded. 

From the screen recording at <https://matrix.org/_matrix/media/v1/download/matrix.org/zcchwczDzqwIUUoIlUcGNzyu>: 

![2018-05-31 18 58 14](https://user-images.githubusercontent.com/192271/40802694-4d070648-650e-11e8-9781-56cdf246e6c9.png)

– in detail: 

![2018-05-31 18 58 14](https://user-images.githubusercontent.com/192271/40802832-a9b38e16-650e-11e8-9c8f-fa0a5c178969.png)

## What's changed? 

With Firefox 56.0.2 and with Waterfox 56.0, when a tab tab appeared wrong in that way it was (in my experience) an almost sure-fire indicator of trouble ahead. Session Restore would be unable to save, and so on. 

With 56.2.0, as far as I can tell, troubles are far more likely to be: 

- purely cosmetic
- negligible. 

If you're unlucky, a tab might become non-apparent after a move from one window to another, but that's probably very edge case, and reasonably easy to workaround. 

```text
$ pkg info waterfox | grep Version
Version        : 56.2.0.31
$ date ; uname -v
Thu 31 May 2018 19:55:13 BST
FreeBSD 12.0-CURRENT #3 r334382: Thu May 31 01:37:12 BST 2018     root@momh167-gjp4-hpelitebook8570p-freebsd:/usr/obj/usr/src/amd64.amd64/sys/GENERIC 
```

**Comment by grahamperrin** [comment]
Um, sorry, on closer inspection: 

- Session Restore does save, and the first save might comprise what's required, 

– however now I find a 1,019-tab session across nine windows saved as a one-tab session. I'll not take further space in this issue, just a heads-up that things aren't right.

**Comment by juanitogan** [comment]
I really have no idea what else is being talked about here so, just as an FYI to anyone else reading this, I haven't had any noticeable issues with 0.8.5.2 and any version of Waterfox since my original post.  And I'm not a light user of tabs.  I generally keep two browsers open (one for programming work, one for other stuff) with maybe 50 tabs each at the moment -- and like to pick up where I left off after rebooting.  But I don't run a lot of other addons or push the features of this addon, Waterfox, or Windows for that matter.  I'm just a database architect and game programmer and like a minimal set of tools that simply work without fussing with things too much.  It seems there may be features in this addon that don't work with Waterfox, but I've forgotten about what those may or may not be.

**Comment by grahamperrin** [comment]
@juanitogan yeah, sorry, there's some in-depth (and untimely) stuff from me that's not easy to absorb. 

The comment with screenshots at https://github.com/Croydon/vertical-tabs-reloaded/issues/42#issuecomment-393928469 is an attempt to make issue 42 more understandable.

**Comment by Croydon** [comment]
# Technical Background

Sorry, for my late reply on this topic, but I kinda sit back a bit on this one and kept watching the developments within Firefox itself and Firefox forks like Waterfox and Palemoon (RIP Cyberfox) and also Firefox related projects like Thunderbird and SeaMonkey.

First of all, I strongly believe that these forks can only survive in the mid and long term when they don't diverge too strongly from upstream Firefox. The resources you need to maintain a browser engine and everything on top is immense. 

The Thunderbird project is struggling for years now to keep up with the changes made upstream because they know as well that if the diverge too much from the Firefox code base they will be already dead without knowing it yet. Due to this I'm incredibly thankful that they came (after very long, often repetitive, very intense discussions) to the conclusion that they will follow upstream Firefox in anything related to the engine and other stuff which makes sense for Thunderbird to have and build additional stuff with the same technologies around it for Thunderbird specific features. For add-ons this means that [they are adopting WebExtensions](https://thunderbird-webextensions.readthedocs.io/en/latest/). They are implementing the same APIs as Firefox when it is useful for a mailing program and developing their own WebExtension-styled APIs for anything email/Thunderbird specific. They will also have a more relaxed attitude when it comes to artificial limitations due to (potential) security advantages, e.g. WebExtension Experiments (they can implement new WebExtension APIs and have direct access to Firefox/Thunderbird/Engine internals) can be used in the stable version of Thunderbird. Firefox is allowing this only for developer versions and only if you explicit opt-in in settings for this. Thunderbird is also keeping old styled add-ons for as long as realistically possible, so there is no hard break from one version to another as it was the case in Firefox (my biggest critic points on how Firefox handled it!). It's still a hard path forward, but I'm hopeful that for add-on developers it will be a lot smoother as it was in Firefox. Old stuff is gradually breaking away while the new APIs are maturing. 

The Thunderbird project is struggling, but they have way more resources than any Firefox fork I know of. Which brings me to the simply conclusion that these forks have to take a similar way forward or they will die due to a code base which is impossible to maintain. Thankfully, the Waterfox project seems to understand this and is taking quite a similar way as Thunderbird: It is merging all upstream changes except the ones which would break existing Waterfox stuff too harsh too quickly, or with other words: Waterfox is adopting WebExtension APIs, add-on developers and add-on users can gradually switch from legacy add-ons to WebExtension ones and the legacy ones will still have to die eventually.


# Legacy VTR, Waterfox and current VTR
I'm glad that the legacy version 0.8.5.2 is still doing a good job in legacy Firefox versions and forks like Waterfox and it can still be a help to people. As @grahamperrin referenced, the legacy version has many quirky behaviours and a lot bugs of all sort. This got a lot better with the WebExtension APIs as WebExtensions finally have a clear structure, clear APIs, clear isolation etc. Sure VTR still has (and will forever) have bugs, but they bugs are way easier to catch, to understand and to fix. Legacy add-ons were often an almost-black-box and almost-impossible to understand what is going on. I believe @grahamperrin can tell a few stories here as well 😄. Even more so when people use non-default Firefox settings or other add-ons which can all influence each other unwillingly. 

Due to all the development background, the way legacy add-ons were designed by their nature, the fact that I'm personally using current, beta and nightly version of Firefox (no ESR, no legacy version, no Firefox fork) and very limited time from my side I came to the conclusion that I won't support new legacy versions of VTR. So version 0.8.5.2 is definitely the last one.

As long as 0.8.5.2 can be of use - great! 
For Waterfox specifically I would suggest to also check out the WebExtensions versions Waterfox is already supporting. Waterfox is lacking behind with WebExtensions APIs so you can't use newer VTR versions, but at the time of writing it is possible to use version [0.9.4](https://addons.mozilla.org/en-US/firefox/addon/vertical-tabs-reloaded/versions/?page=1#version-0.9.4) in the current version of Waterfox and a very quick test didn't bring up any major issues.

**To generalize this: For Waterfox users I would currently recommend to check out the version overview of VTR in Waterfox, see what is the latest version which is marked as compatible with your browser and use this version. https://addons.mozilla.org/en-US/firefox/addon/vertical-tabs-reloaded/versions/**

Please note, that when you use older VTR versions you might run into bugs which are already fixed in newer versions etc. but there is no (maintainable) way around this.

**Since I don't have as much time as I would like and due to the fact that I personally don't use Waterfox and that it is lacking behind WebExtension API support, I do not _- officially -_ support Waterfox currently.** This might change in the future when any of this circumstance are changing.

However, please still feel free to either comment here on this issue or contact me via Matrix/Riot when you are using VTR with Waterfox and run into any problems. I _**might**_ look into it, please just don't _**expect**_ me to provide help with Waterfox+VTR.

Thanks for using VTR.
Cheers!

**Comment by juanitogan** [comment]
@Croydon  - Thank you for the lengthy response.  I totally respect your decision.  I don't have time to maintain all my open-source activities either.  To be clear, I don't think I was looking for any more major work on 0.8.5.2 as much as I was just thinking about a fork or something to help others find a vertical tab tool that can also hide the horizontal tabs.  And, the latest versions of VTR compatible with Waterfox don't do that (unless I've missed something somewhere).  (Yeah, I've seen some unsupported CSS tricks for such things, but I don't want to get into that.)

Regarding Waterfox, I only switched to it because I really really really like vertical tabs.  But, I don't like them so much that I'm willing to lose twice the real estate and endure twice the clutter.  When or if vertical tabs fail on Waterfox, I'll abandon it and go looking for another solution.  But, I don't read the future of Waterfox like you do.  The dev seems super dedicated to preserving the old addons -- why else would he create his own store (or whatever he called it) for them?  Anyhow, that hardly matters now -- if the old VTR code is an annoying black box, then, yeah, leave it for more enjoyable work.  Maybe someone else will fork it and run with it if there's still life there.

Now, I'll head over to Bugzilla and try to give them a kick in the right direction. 😉
