### ISSUE TITLE
Compatibility to Tab Mix Plus

### ISSUE THREAD

**Issue by tbs** [Croydon/vertical-tabs-reloaded#19]
Any chance to you make it compatible to Tab Mix Plus extension?

Result if both addon are active:

![Tab Mix Plus](https://cloud.githubusercontent.com/assets/768954/13868034/cf624a5c-eca3-11e5-84c1-fb2ae23d745c.png)

**Comment by Croydon** [comment]
I'm looking into it. Basically there is only one initialization problem of Tab Mix Plus in the inital window. If you open a new one, it will (more or less) work there. 

With the commit 7be993b61838b47de1ab3117932e5087b888c432 I have fixed the basic style, so that it is actually useable. This will be part of the next update.

So if the initialization problem is fixed both add-ons should work together. Even there are definitely some minor visual flaws.

**Comment by Croydon** [comment]
TMP and VTR will be compatible soon. :tada: 

More information:
http://tabmixplus.org/forum/viewtopic.php?f=4&t=19551

**Comment by Croydon** [comment]
https://bitbucket.org/onemen/tabmixplus/commits/3d956f095d29
https://bitbucket.org/onemen/tabmixplus/commits/04125996caa2a4fcee4493871cb224e824ed59fe

**Comment by Croydon** [comment]
https://bitbucket.org/onemen/tabmixplus/commits/86dd60e05632ea711b0535f983ef1546e8c1e49c

**Comment by Croydon** [comment]
@tbs 
VTR v0.6.2 or newer is supposed to work fine with Tab Mix Plus v0.5.0 or newer. Please report any further bugs and unexpected behaviour. Thanks.
