### ISSUE TITLE
Option to hide resize border

### ISSUE THREAD

**Issue by tbs** [Croydon/vertical-tabs-reloaded#21]
Would be good

**Comment by yafp** [comment]
which border are you talking about?

**Comment by tbs** [comment]
The border where you can drag and resize "tabs bar".

**Comment by yafp** [comment]
What would be the advantage of that?

In most cases you see a border anyways, due to different colors of tabbar and current tab-content-background

**Comment by tbs** [comment]
Its a little annoying to see this "huge" border there, also to avoid resizing my mistake, like if you try drag scrollbars.

**Comment by widget-** [comment]
It lets Personas (or whatever they're called) bleed through the gap. I'd actually be ok with it if it had a background of its own.

![screen shot 2016-05-13 at 9 35 58 am](https://cloud.githubusercontent.com/assets/7691630/15251346/8ad2bd5a-18ee-11e6-918c-26d2331bf1da.png)

**Comment by Croydon** [comment]
@widget- @yafp @tbs 
The splitter will be a lot more subtle starting with v0.7.0. 
In the Dark theme the splitter will have the same color as the tabbrowser, in the Light theme it will have the same color as a tab on hover right now. Furthermore the splitter doesn't have a border anymore in these two themes.

The splitter in the Darwin theme will be unchanged, since it is already invisible there.
No changes for the Linux and Windows theme so far, these themes needs a major rework anyway. (Okay, except a small margin fix for the Windows theme splitter). I'm also thinking about merging them both to a minimalistic theme.

Preview:
![dark](https://cloud.githubusercontent.com/assets/1593194/16059299/b9638994-3282-11e6-8833-770f7f9a126c.PNG)
![darkscroll](https://cloud.githubusercontent.com/assets/1593194/16059300/b9652718-3282-11e6-8892-1815b0d1d0b2.PNG)
![light](https://cloud.githubusercontent.com/assets/1593194/16059302/b96c7540-3282-11e6-9185-f17d2ca90e3e.PNG)
![lightscroll](https://cloud.githubusercontent.com/assets/1593194/16059301/b9679b24-3282-11e6-9f3b-74d926563caa.PNG)

Please let me know what you think of that change! 😊

**Comment by Croydon** [comment]
To make it clearer: No, there won't be an option to hide the splitter completely, but it will be more subtle. The Darwin theme already makes the splitter invisible and in the future users can use custom themes, see #40.

**Comment by Croydon** [comment]
I just noticed that the splitter color for the Dark theme was not well chosen. I changed it to the background color of a selected tab, so that there is a visible divider if you open the add-on page. Done in 4cb4e2e3373e9dd9874aca1bf8a2cdcca269a6ec

**Comment by yafp** [comment]
@Croydon i like the previews
