### ISSUE TITLE
Can't click some page elements when VTR is loaded and visible

### ISSUE THREAD

**Issue by JonathanWheeler** [Croydon/vertical-tabs-reloaded#270]
Add-on version: 0.13.1
Firefox version: 107.0
OS + OS-Version: macOS Ventura 13.0
Other tab + user interface related add-ons: 

On certain pages, I can't click on certain links/elements. I've tried disabling all other extensions, but the issue persists until I either disable VTR or hide its pane. 

For example, a recent example that I remember is that I can't click "View larger map" on the left side of the map at the bottom of [this](https://www.sanjuan.edu/Domain/4) page. Once I hide or disable VTR, I can.

Thank you for your work!

**Comment by Croydon** [comment]
I think that this is a website issue.

To test it hide the VTR sidebar and resize your Firefox window to a smaller width. On certain widths the link can't be clicked, on others it can. So basically you run into this issue because the sidebar takes away width and surfaces the issue, but the issue is for the website to fix.
