### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by jzakula** [Croydon/vertical-tabs-reloaded#273]
HI, I love Vertical Tabs Reloaded. I have used it for years. I often am working on several projects at the same time. As a dev sometimes I get a couple hundred tabs open trying to tie several technologies together. Having more tabs sometimes needs a little more control. I wonder if you would consider giving the user a choice to choose different color combos for different tags to make it easier to jump from one subject to the next and back again.
Once again, great add-in.

**Comment by Croydon** [comment]
> I wonder if you would consider giving the user a choice to choose different color combos for different tags to make it easier to jump from one subject to the next and back again.

This sounds a lot like asking for better integration with tab containers: https://github.com/Croydon/vertical-tabs-reloaded/issues/92

Right now, VTR does not integrate with tab containers or tab group add-ons (https://github.com/Croydon/vertical-tabs-reloaded/issues/4) and therefore has no concept of grouping tabs. Since there is no grouping there is also no way to give them a specific colours right now.

However, this is on the roadmap, but will probably take time until I actually implement it.
