### ISSUE TITLE
publication to mozilla addons for auto-update

### ISSUE THREAD

**Issue by woj-tek** [Croydon/vertical-tabs-reloaded#5]
This is more of a question but are there any plans to publish the add-on to mozilla website so it would be auto-updated?

**Comment by Croydon** [comment]
Since Firefox will reject soon all installations of addons which aren't signed, yes.
In fact I have already uploaded it, but it's still in the waiting list.

**Comment by woj-tek** [comment]
Great, thanks! :-)

**Comment by steampunklolcat** [comment]
It was shortly available on amo, why was it removed again?

**Comment by Croydon** [comment]
I did hide the addon on AMO for the time being, because the addon still has some serious issues and I don't want to get more publicly before some stuff is fixed. 

Unfortunately, my time for this project is very limited and I'm a Firefox addon newbie. So please don't expect that everything is done in two days. Contributings are very appreciated. After all I just started this fork because I couldn't find any active fork of the original addon or a good addon which is doing the same.

**Comment by steampunklolcat** [comment]
That's fair enough. It has worked fine here so far though.

**Comment by woj-tek** [comment]
OK, given that Mozilla is advancing the idea of blocking unsigned extensions (bleh! :/) are there plans to un-hide the extension on AMO? I'm using it extensively almost since beginning and find it very stable.

**Comment by Croydon** [comment]
I have decided to list the addon publicly, even I still consider it as not-so-stable.

You can install it now from https://addons.mozilla.org/firefox/addon/vertical-tabs-reloaded/

An update, which introduces, for instance, the feature that the tabbar is getting hidden in fullscreen, is already in the waitinglist.
