### ISSUE TITLE
Toolbar doesn't appear in Firefox's customize page

### ISSUE THREAD

**Issue by m0n** [Croydon/vertical-tabs-reloaded#60]
Add-on version: 0.7.0
Firefox version: standard 47.1 or developer 50.0a2 (2016-08-06)
OS + OS-Version: Win7 x64
Other tab + user interface related add-ons: none

Hmmm... Really, am I the only person who can't add items to the Toolbar? Plugin disabled I able to add items and when I enable plugin, these items appears right.

May I missed some serious info about this topic :( ?

**Comment by Croydon** [comment]
This is an already know bug, but thanks for reporting anyway :)

**Comment by Croydon** [comment]
Outdated issue because of the move towards WebExtensions, see #13 for more information.

VTR will have a custom toolbar in the feature, therefore not touching the default Firefox UI elements anymore.

Customization of the custom toolbar will be another issue then and likely won't work over the Firefox customization feature.
