### ISSUE TITLE
switch to packages.json

### ISSUE THREAD

**Issue by panosl** [Croydon/vertical-tabs-reloaded#7]
Is it possible to switch on package.json and be able to leverage cfx for easier testing and is it worth it?

**Comment by Croydon** [comment]
I have made a try a few days ago, but runned into a few problems. E. g. no options were displayed. 
I will dig deeper into it as soon as I can :)

**Comment by Croydon** [comment]
@panosl I will soon move it to package.json + JPM

**Comment by panosl** [comment]
Finally you've picked up development again :P

**Comment by Croydon** [comment]
@yafp The migration to package.json was done with f67563bb2b9c829754b6b8e8cc37dedbbe3a7eb1, however, it is not ready yet, since it introduced a major issue: When tabs are getting closed it lefts often a blank space where the tab was, also sometimes the tabs aren't getting really closed, they seem to be just invisble till you restart Firefox.

I am currently a bit clueless about what exactly I broke and how to fix it. Any hints and help would be highly appreciated as always :)

**Comment by yafp** [comment]
@Croydon thx

**Comment by Croydon** [comment]
@yafp I have tried it now with four different profiles on two computers and I only get this problem with a version of the branch new_themes, so it is kinda hard to debug for me. However, it seems like you wouldn't be the only one who has this issue already with the 0.3.2 version.

Could you perhaps check out if you have this bug in 0.3.0 as well? You could install the version from https://addons.mozilla.org/de/firefox/addon/vertical-tabs-reloaded/versions/?page=1#version-0.3
If you try it please disable temporary the auto update for the addon to make sure that it doesn't update itself and make one restart of Firefox after installing and before testing.

**Comment by yafp** [comment]
@Croydon
alright - started using 0.3.0 now - gonna report back as soon as i notice something
