### ISSUE TITLE
Latest version of the addon (0.8.0) incompatible with current version of Firefox (50.1.0)

### ISSUE THREAD

**Issue by BMarinov** [Croydon/vertical-tabs-reloaded#76]
Add-on version: 0.800
Firefox version: 50.1.0
OS + OS-Version: Win 10 Pro
Other tab + user interface related add-ons: Tab Groups

I recently tried to install the version on a PC that was already running FF 50.1.0; I got an error message stating that the addon is incompatible with this version of firefox. On the following page I can see that the version im currently running, 0.7.1, is compatible:
https://addons.mozilla.org/en-us/firefox/addon/vertical-tabs-reloaded/versions/

Is 0.8.0 planned for future Firefox releases that may be from the beta/nightly channel? If thats the case then that may not exactly be an issue, but still such a version shouldnt probably been published - people searching for the addon may be left with the impression that there is no compatible version available.

**Comment by Croydon** [comment]
Firefox 51.0 was released yesterday. v0.8.0 was indeed a few days online earlier. I realized that I had the possibility to disable the version on AMO after the version got approved so I will do this the next time such a situation occurs.

I general I think that AMO should handle this smarter, but that's an argument for another place. 
With the release of FF v51 yesterday the issue is solving itself fast.

Thanks for your feedback :)
