### ISSUE TITLE
Audio Playing Icon is not visible

### ISSUE THREAD

**Issue by duzers** [Croydon/vertical-tabs-reloaded#97]
Add-on version: 0.8.3.1
Firefox version:54b9 x64
OS + OS-Version:Windows 7 Pro x64
Other tab + user interface related add-ons:  -

We can enable icon of audio playing (about:config >> browse.tabs.showAudioPlayingIcon) but we can't see this icon.

**Comment by Croydon** [comment]
Unfortunately, it broke with some Firefox update, but my full concentration is now on porting the add-on to a WebExtension. You can get more information at #13.

I will close this issue as soon as I have implemented a sound icon/muting feature into the WebExtension part.

Sorry, for the inconvenience in the meantime. You could use the context menu on each tab to mute/unmute tabs.

**Comment by fotonmoton** [comment]
confirm that icon doesn't appear.
OS: Windows 10 (x64)
Firefox: 53.0.3 (32-bit)
VTR: 0.8.3.1
@Croydon view your answer. I salute your efforts to port add-on to WebExtension and wish you smooth transition :)

**Comment by joanbm** [comment]
Adding this to userChrome.css or with Stylish works for me.

```
@namespace url("http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul");
.tab-icon-sound[soundplaying]:not(.fix-for-stylish-extension-priority)
{
	list-style-image: url("chrome://browser/skin/tabbrowser/tab-audio.svg#tab-audio") !important;
}

.tab-icon-sound[muted]:not(.fix-for-stylish-extension-priority)
{
	list-style-image: url("chrome://browser/skin/tabbrowser/tab-audio.svg#tab-audio-muted") !important;
}

.tabbrowser-tab:not(:hover):not([selected="true"]):not(.fix-for-stylish-extension-priority) .tab-close-button {
	visibility: visible !important;
}
```

I haven't looked much into it, but it looks like the extension is overriding the default mute icons, and for some reason it doesn't work. This just reverts the list-style-image attribute back to its original value, which appears to work.

The last clause is for optional / for usability purposes (to prevent the mute button from moving when hovering an inactive tab).

**Comment by joanbm** [comment]
They have changed the paths to the icons in FF55: https://bugzilla.mozilla.org/show_bug.cgi?id=1368428, so the icons no longer appear with the old fix

New fix:

```
@namespace url("http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul");
.tab-icon-sound[soundplaying]:not(.fix-for-stylish-extension-priority)
{
	list-style-image: url("chrome://browser/skin/tabbrowser/tab-audio-playing.svg") !important;
}

.tab-icon-sound[muted]:not(.fix-for-stylish-extension-priority)
{
	list-style-image: url("chrome://browser/skin/tabbrowser/tab-audio-muted.svg") !important;
}

.tabbrowser-tab:not(:hover):not([selected="true"]):not(.fix-for-stylish-extension-priority) .tab-close-button {
	visibility: visible !important;
}
```

**Comment by Croydon** [comment]
@joanbm Thank you so much for the Bugzilla link and the example fix. You did save me quite some time with that :)

**Comment by joanbm** [comment]
@Croydon Glad I could be of help!

I checked the commit and see that you included the "visibility: visible !important" part, this part was just to make the close buttons always show, but it's not related to the audio visible icon (it's just that I like it that way, because otherwise the audio playing icon moves when you hover over it).

However note that it doesn't seem to do anything in the state you've included it (unless I'm missing something), because in vertical-tabs-reloaded there's another "visibility: collapse !important" with more priority:

https://imgur.com/a/aFNV2

So unless I'm missing something, I think you can remove the "visiblity: visible !important" line, because the "visiblity: collapse !important" has a greater precedence and it's being applied anyway. Or if you wanted to make the close buttons always show, you can remove all visibility styles from your addon and then the Firefox default "visibility: visible" should work.
